/**
 * Seed all 103 products from XLSX catalog data to the live Payload CMS.
 * Uses REST API so it works against any running server (local or production).
 *
 * Usage:
 *   PAYLOAD_URL=https://carryish.ai node --import tsx/esm scripts/seed-xlsx-products.ts
 *   PAYLOAD_URL=http://localhost:3000 node --import tsx/esm scripts/seed-xlsx-products.ts
 */

import 'dotenv/config'

const BASE_URL = process.env.PAYLOAD_URL || 'http://localhost:3000'
const EMAIL = process.env.PAYLOAD_EMAIL || 'demo-author@example.com'
const PASSWORD = process.env.PAYLOAD_PASSWORD || 'password'

function log(msg: string) {
  console.log(`[seed-xlsx] ${msg}`)
}

async function login(): Promise<string> {
  const res = await fetch(`${BASE_URL}/api/users/login`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ email: EMAIL, password: PASSWORD }),
  })
  if (!res.ok) throw new Error(`Login failed (${res.status}): ${await res.text()}`)
  const data = await res.json()
  log(`Logged in as ${EMAIL}`)
  return data.token
}

async function findBySlug(collection: string, slug: string, token: string): Promise<any | null> {
  const res = await fetch(
    `${BASE_URL}/api/${collection}?where[slug][equals]=${encodeURIComponent(slug)}&limit=1`,
    { headers: { Authorization: `JWT ${token}` } },
  )
  if (!res.ok) return null
  const data = await res.json()
  return data.docs?.[0] || null
}

async function createDoc(collection: string, data: any, token: string): Promise<any> {
  const res = await fetch(`${BASE_URL}/api/${collection}`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `JWT ${token}`,
    },
    body: JSON.stringify(data),
  })
  if (!res.ok) {
    const text = await res.text()
    throw new Error(`Failed to create ${collection}: ${res.status} ${text}`)
  }
  return res.json()
}

// ─── Brand data (54 brands) ───

const brands = [
  { name: 'Addmotor', slug: 'addmotor', websiteUrl: 'https://www.addmotor.com', description: 'Budget-friendly DTC cargo bikes on Shopify. Dual battery options on some models.' },
  { name: 'ALSO', slug: 'also', websiteUrl: 'https://ridealso.com', description: 'Rivian spinoff building cargo quads. Amazon contract for last-mile delivery.' },
  { name: 'Aventon', slug: 'aventon', websiteUrl: 'https://www.aventon.com', description: 'DTC brand that punches above its price. GPS tracking and alarm on sub-$2K cargo bikes.' },
  { name: 'Benno', slug: 'benno', websiteUrl: 'https://www.bennobikes.com', description: 'Founded by the creator of Electra. Bosch-powered compacts and longtails.' },
  { name: 'Bike Friday', slug: 'bike-friday', websiteUrl: 'https://www.bikefriday.com', description: 'Oregon-based custom folding bikes. The Haul-a-Day is their cargo entry.' },
  { name: 'Blix', slug: 'blix', websiteUrl: 'https://www.blixbike.com', description: 'Swedish-designed, California-assembled DTC e-bikes. Clean lines, competitive pricing.' },
  { name: 'Bunch Bikes', slug: 'bunch-bikes', websiteUrl: 'https://www.bunchbike.com', description: 'Texas family bike brand. Front-loader trikes built for hauling kids.' },
  { name: 'Butchers & Bicycles', slug: 'butchers-and-bicycles', websiteUrl: 'https://www.butchersandbicycles.com', description: 'Danish tilting cargo trike. Patented leaning mechanism for cornering.' },
  { name: 'Buzz Bicycles', slug: 'buzz-bicycles', websiteUrl: 'https://www.buzzbicycles.com', description: 'Budget DTC brand offering affordable cargo and utility e-bikes.' },
  { name: 'Cannondale', slug: 'cannondale', websiteUrl: 'https://www.cannondale.com', description: 'Major bike brand entering cargo with the Cargowagen Neo series.' },
  { name: 'Carqon', slug: 'carqon', websiteUrl: 'https://www.carqon.com', description: 'Dutch premium front-loaders with integrated child safety features.' },
  { name: 'CERO Bikes', slug: 'cero-bikes', websiteUrl: 'https://www.cerobicycles.com', description: 'California cargo bike startup. Compact semi-recumbent design.' },
  { name: 'Christiania Bikes', slug: 'christiania-bikes', websiteUrl: 'https://www.christianiabikesamerica.com', description: 'Danish trike maker since 1984. The OG cargo bike brand.' },
  { name: 'Coaster Cycles', slug: 'coaster-cycles', websiteUrl: 'https://www.coastercycles.com', description: 'Small-batch cargo bikes from Portland.' },
  { name: 'ENGWE', slug: 'engwe', websiteUrl: 'https://us.engwe.com', description: 'Chinese DTC brand offering budget longtails and utility e-bikes.' },
  { name: 'Ferla', slug: 'ferla', websiteUrl: 'https://www.ferlafamilybikes.com', description: 'Family cargo bikes and commercial vending trikes on Shopify.' },
  { name: 'Fernhay', slug: 'fernhay', websiteUrl: 'https://fernhay.com', description: 'UK last-mile logistics e-trikes for commercial fleets.' },
  { name: 'Fiido', slug: 'fiido', websiteUrl: 'https://www.fiido.com', description: 'Chinese DTC brand. The T2 is their longtail cargo entry.' },
  { name: 'GoCycle', slug: 'gocycle', websiteUrl: 'https://gocycle.com', description: 'British folding e-bike brand. Premium compact design.' },
  { name: 'Heybike', slug: 'heybike', websiteUrl: 'https://www.heybike.com', description: 'DTC brand with affordable longtail and cargo options.' },
  { name: 'Himiway', slug: 'himiway', websiteUrl: 'https://himiwaybike.com', description: 'DTC fat-tire brand entering cargo with the Big Dog.' },
  { name: 'Honda', slug: 'honda', websiteUrl: 'https://fastport.honda.com', description: 'Fastport is Honda\'s upcoming e-cargo concept bike.' },
  { name: 'Icicle Tricycles', slug: 'icicle-tricycles', websiteUrl: 'https://icetrikes.com', description: 'Portland vending and commercial cargo trikes.' },
  { name: 'KBO', slug: 'kbo', websiteUrl: 'https://www.kbobike.com', description: 'Budget DTC e-bike brand with cargo-capable models.' },
  { name: 'Larry vs Harry', slug: 'larry-vs-harry', websiteUrl: 'https://www.larryvsharry.com', description: 'Danish maker of the Bullitt — the sports car of cargo bikes.' },
  { name: 'Lectric', slug: 'lectric', websiteUrl: 'https://lectricebikes.com', description: 'King of budget DTC. The XPedition line offers insane value.' },
  { name: 'Madsen', slug: 'madsen', websiteUrl: 'https://www.madsencycles.com', description: 'Utah family bucket bike. Iconic rear cargo bucket design.' },
  { name: 'Magnum', slug: 'magnum', websiteUrl: 'https://magnumbikes.com', description: 'Israel-designed e-bikes. The Payload is their cargo model.' },
  { name: 'MOD Bikes', slug: 'mod-bikes', websiteUrl: 'https://mod-bikes.com', description: 'Berlin-designed DTC longtails and utility e-bikes.' },
  { name: 'Mokwheel', slug: 'mokwheel', websiteUrl: 'https://www.mokwheel.com', description: 'Chinese DTC brand with cargo-capable utility e-bikes.' },
  { name: 'Momentum', slug: 'momentum', websiteUrl: 'https://www.momentum-biking.com', description: 'Giant sub-brand. Practical utility and cargo e-bikes.' },
  { name: 'Mongoose', slug: 'mongoose', websiteUrl: 'https://www.mongoose.com', description: 'Classic BMX brand with an e-cargo entry.' },
  { name: 'Mubea', slug: 'mubea', websiteUrl: 'https://us.mubea-umobility.com', description: 'German automotive supplier building commercial e-cargo vehicles.' },
  { name: 'Nihola', slug: 'nihola', websiteUrl: 'https://nihola.com', description: 'Danish cargo trike specialist. Box trikes for families and business.' },
  { name: 'Omnium Cargo', slug: 'omnium-cargo', websiteUrl: 'https://omniumcargo.us', description: 'Danish performance cargo bikes. Lightweight front-loaders.' },
  { name: 'Pedego', slug: 'pedego', websiteUrl: 'https://www.pedegoelectricbikes.com', description: 'Premium DTC e-bike brand with dealer network.' },
  { name: 'Rad Power Bikes', slug: 'rad-power-bikes', websiteUrl: 'https://www.radpowerbikes.com', description: 'Seattle DTC pioneer. RadWagon is their flagship cargo bike.' },
  { name: 'Radio Flyer', slug: 'radio-flyer', websiteUrl: 'https://www.radioflyer.com', description: 'Classic toy wagon brand now making e-cargo bikes for families.' },
  { name: 'Ride1Up', slug: 'ride1up', websiteUrl: 'https://ride1up.com', description: 'San Diego DTC e-bike brand offering cargo-capable models.' },
  { name: 'Riese & Müller', slug: 'riese-and-muller', websiteUrl: 'https://www.r-m.de', description: 'German premium e-bikes. Packster and Load are cargo flagships.' },
  { name: 'Rytle', slug: 'rytle', websiteUrl: 'https://rytle.com', description: 'German last-mile logistics cargo bike platform.' },
  { name: 'Specialized', slug: 'specialized', websiteUrl: 'https://www.specialized.com', description: 'Major bike brand. Globe Haul is their cargo line.' },
  { name: 'Surface 604', slug: 'surface-604', websiteUrl: 'https://surface604bikes.com', description: 'Canadian DTC e-bike brand with utility cargo models.' },
  { name: 'Surly', slug: 'surly', websiteUrl: 'https://surlybikes.com', description: 'Minneapolis steel bike brand. Big Easy is their e-cargo longtail.' },
  { name: 'Tenways', slug: 'tenways', websiteUrl: 'https://us.tenways.com', description: 'Chinese premium DTC brand entering cargo bikes.' },
  { name: 'Tern', slug: 'tern', websiteUrl: 'https://store.ternbicycles.com', description: 'Folding and cargo bike specialist. GSD, HSD, Quick Haul are cargo hits.' },
  { name: 'Trek', slug: 'trek', websiteUrl: 'https://www.trekbikes.com', description: 'Major bike brand. Fetch+ is their cargo longtail.' },
  { name: 'Triobike', slug: 'triobike', websiteUrl: 'https://triobike.com', description: 'Danish premium cargo trikes with modular front boxes.' },
  { name: 'Urban Arrow', slug: 'urban-arrow', websiteUrl: 'https://www.urbanarrow.com', description: 'Dutch cargo bike leader. Family and Shorty are category-defining.' },
  { name: 'Velotric', slug: 'velotric', websiteUrl: 'https://velotricbike.com', description: 'DTC brand with competitive pricing on utility and cargo e-bikes.' },
  { name: 'Virtue Cycles', slug: 'virtue-cycles', websiteUrl: 'https://virtuecycles.com', description: 'Philadelphia cargo bike brand. Gondoliere trikes.' },
  { name: 'Worksman Cycles', slug: 'worksman-cycles', websiteUrl: 'https://www.worksmancycles.com', description: 'NYC industrial trike maker since 1898. Commercial workhorses.' },
  { name: 'Xtracycle', slug: 'xtracycle', websiteUrl: 'https://xtracycle.com', description: 'Invented the longtail category. The Stoker is their flagship.' },
  { name: 'Yuba', slug: 'yuba', websiteUrl: 'https://yubabikes.com', description: 'Sausalito cargo bike specialist. Spicy Curry, Mundo, Kombi are staples.' },
]

// ─── Product data (103 products from XLSX) ───

const products = [
  {
    name: 'Addmotor GRAOOPRO',
    slug: 'addmotor-graoopro',
    brand: 'addmotor',
    category: 'cargo-bike',
    price: 1999,
    affiliateUrl: 'https://www.addmotor.com/products/graoopro',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'longtail',
    motorBrand: 'Generic',
    motorPosition: 'hub-rear',
    motorNominalWatts: 750,
    motorPeakWatts: 1000,
    motorTorqueNm: 80,
    motorType: '750W Hub (Generic)',
    bikeClass: 'class-2',
    batteryWh: 960,
    dualBatteryCapable: true,
    dualBatteryWh: 1920,
    weightLbs: 85,
    maxSystemWeightLbs: 450,
    salesModel: 'direct-to-consumer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Budget Longtail' }],
  },
  {
    name: 'Addmotor E-325',
    slug: 'addmotor-e-325',
    brand: 'addmotor',
    category: 'cargo-bike',
    price: 3699,
    affiliateUrl: 'https://www.addmotor.com/products/e-325',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'front-box',
    motorBrand: 'Bafang',
    motorPosition: 'hub-rear',
    motorNominalWatts: 750,
    motorType: '750W Hub (Bafang)',
    bikeClass: 'class-2',
    maxSystemWeightLbs: 550,
    salesModel: 'direct-to-consumer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Budget Front-loader' }],
  },
  {
    name: 'Addmotor M-330',
    slug: 'addmotor-m-330',
    brand: 'addmotor',
    category: 'cargo-bike',
    price: 4399,
    affiliateUrl: 'https://www.addmotor.com/products/m-330',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'trike',
    motorBrand: 'Generic',
    motorNominalWatts: 750,
    motorType: '750W (Generic)',
    bikeClass: 'class-2',
    salesModel: 'direct-to-consumer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Family Trike' }],
  },
  {
    name: 'ALSO TM-Q',
    slug: 'also-tm-q',
    brand: 'also',
    category: 'cargo-bike',
    price: 0,
    affiliateUrl: 'https://ridealso.com/products/quad',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'trike',
    motorBrand: 'Proprietary',
    motorType: 'DreamRide pedal-by-wire (Proprietary)',
    bikeClass: 'class-1',
    dualBatteryCapable: true,
    maxSystemWeightLbs: 400,
    salesModel: 'direct-to-consumer',
    availableIn: 'Spring 2026',
    bestFor: [{ tag: '4-Wheel Quad' }],
  },
  {
    name: 'Aventon Abound SR',
    slug: 'aventon-abound-sr',
    brand: 'aventon',
    category: 'cargo-bike',
    price: 2199,
    affiliateUrl: 'https://www.aventon.com/products/abound-sr-ebike',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'midtail',
    motorBrand: 'Proprietary',
    motorPosition: 'hub-rear',
    motorNominalWatts: 750,
    motorPeakWatts: 950,
    motorTorqueNm: 80,
    motorType: '750W Hub (Proprietary)',
    bikeClass: 'class-2',
    batteryWh: 708,
    weightLbs: 80,
    maxSystemWeightLbs: 440,
    salesModel: 'direct-to-consumer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Mid-Range Midtail' }],
  },
  {
    name: 'Aventon Abound LR',
    slug: 'aventon-abound-lr',
    brand: 'aventon',
    category: 'cargo-bike',
    price: 1999,
    affiliateUrl: 'https://www.aventon.com/products/abound-lr-ebike',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'longtail',
    motorBrand: 'Proprietary',
    motorPosition: 'hub-rear',
    motorNominalWatts: 750,
    motorPeakWatts: 1188,
    motorTorqueNm: 80,
    motorType: '750W Hub (Proprietary)',
    bikeClass: 'class-2',
    batteryWh: 708,
    weightLbs: 82,
    maxSystemWeightLbs: 440,
    salesModel: 'direct-to-consumer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Mid-Range Longtail' }],
  },
  {
    name: 'Benno Boost 10D EVO 5',
    slug: 'benno-boost-10d-evo-5',
    brand: 'benno',
    category: 'cargo-bike',
    price: 3699,
    affiliateUrl: 'https://www.bennobikes.com/e-bikes/boost/',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'longtail',
    motorBrand: 'Bosch',
    motorPosition: 'mid-drive',
    motorNominalWatts: 250,
    motorTorqueNm: 65,
    motorType: 'Performance / CX / Speed (Bosch)',
    bikeClass: 'class-1',
    batteryWh: 400,
    weightLbs: 65,
    maxSystemWeightLbs: 440,
    salesModel: 'dealer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Premium Longtail' }],
  },
  {
    name: 'Benno 46er 10D EVO 1',
    slug: 'benno-46er-10d-evo-1',
    brand: 'benno',
    category: 'cargo-bike',
    price: 4999,
    affiliateUrl: 'https://www.bennobikes.com/e-bikes/46er/',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'compact',
    motorBrand: 'Bosch',
    motorPosition: 'mid-drive',
    motorNominalWatts: 250,
    motorTorqueNm: 85,
    motorType: 'Performance CX / Speed (Bosch)',
    bikeClass: 'class-1',
    batteryWh: 500,
    weightLbs: 60,
    maxSystemWeightLbs: 420,
    salesModel: 'dealer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Premium Compact' }],
  },
  {
    name: 'Benno eJoy 10D',
    slug: 'benno-ejoy-10d',
    brand: 'benno',
    category: 'cargo-bike',
    price: 2999,
    affiliateUrl: 'https://www.bennobikes.com/e-bikes/ejoy/',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'longtail',
    motorBrand: 'Bosch',
    motorPosition: 'mid-drive',
    motorNominalWatts: 250,
    motorTorqueNm: 50,
    motorType: 'Active Plus / Performance (Bosch)',
    bikeClass: 'class-1',
    batteryWh: 400,
    weightLbs: 55,
    maxSystemWeightLbs: 400,
    salesModel: 'dealer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Utility' }],
  },
  {
    name: 'Benno RemiDemi 9D',
    slug: 'benno-remidemi-9d',
    brand: 'benno',
    category: 'cargo-bike',
    price: 3299,
    affiliateUrl: 'https://www.bennobikes.com/e-bikes/remidemi/',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'compact',
    motorBrand: 'Bosch',
    motorPosition: 'mid-drive',
    motorNominalWatts: 250,
    motorTorqueNm: 65,
    motorType: 'Performance / Sport (Bosch)',
    bikeClass: 'class-1',
    batteryWh: 400,
    weightLbs: 60,
    maxSystemWeightLbs: 400,
    salesModel: 'dealer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Premium Compact' }],
  },
  {
    name: 'Benno RemiDemi XL 9D EVO 3',
    slug: 'benno-remidemi-xl-9d-evo-3',
    brand: 'benno',
    category: 'cargo-bike',
    price: 4199,
    affiliateUrl: 'https://www.bennobikes.com/e-bikes/remidemi-xl/',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'midtail',
    motorBrand: 'Bosch',
    motorPosition: 'mid-drive',
    motorNominalWatts: 250,
    motorTorqueNm: 75,
    motorType: 'Performance Smart / Sport Smart (Bosch)',
    bikeClass: 'class-1',
    batteryWh: 545,
    weightLbs: 65,
    maxSystemWeightLbs: 420,
    salesModel: 'dealer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Premium Midtail' }],
  },
  {
    name: 'Bike Friday Haul-a-Day Elite',
    slug: 'bike-friday-haul-a-day-elite',
    brand: 'bike-friday',
    category: 'cargo-bike',
    price: 2500,
    affiliateUrl: 'https://www.bikefriday.com/product/bike-friday-haul-a-day-elite-cargo-bike/',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'longtail',
    motorBrand: 'Optional',
    motorType: 'E-assist kit (Optional)',
    weightLbs: 33,
    maxSystemWeightLbs: 440,
    salesModel: 'direct-to-consumer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Non-Electric Longtail' }],
  },
  {
    name: 'Blix Packa Genie',
    slug: 'blix-packa-genie',
    brand: 'blix',
    category: 'cargo-bike',
    price: 2099,
    affiliateUrl: 'https://www.blixbike.com/products/packa-electric-cargo-bike',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'compact',
    motorBrand: 'Generic',
    motorPosition: 'hub-rear',
    motorNominalWatts: 750,
    motorPeakWatts: 1350,
    motorType: '750W Geared Hub (Generic)',
    bikeClass: 'class-2',
    batteryWh: 672,
    dualBatteryCapable: true,
    dualBatteryWh: 1344,
    weightLbs: 76,
    maxSystemWeightLbs: 400,
    salesModel: 'direct-to-consumer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Mid-Range Compact' }],
  },
  {
    name: 'Bunch Bikes The Original 4+',
    slug: 'bunch-bikes-the-original-4',
    brand: 'bunch-bikes',
    category: 'cargo-bike',
    price: 6739,
    affiliateUrl: 'https://www.bunchbike.com/products/the-original-4-upgraded-electric-cargo-bike-for-families',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'front-box',
    motorBrand: 'Generic',
    motorPosition: 'hub-rear',
    motorNominalWatts: 500,
    motorTorqueNm: 45,
    motorType: '500W Hub (Generic)',
    bikeClass: 'class-1',
    batteryWh: 614,
    weightLbs: 168,
    maxSystemWeightLbs: 600,
    salesModel: 'direct-to-consumer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Family Front-loader Trike' }],
  },
  {
    name: 'Bunch Bikes The K9 4+',
    slug: 'bunch-bikes-the-k9-4',
    brand: 'bunch-bikes',
    category: 'cargo-bike',
    price: 6999,
    affiliateUrl: 'https://www.bunchbike.com/products/the-k9-4-electric-cargo-bike-for-dogs',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'front-box',
    motorBrand: 'Generic',
    motorPosition: 'hub-rear',
    motorNominalWatts: 500,
    motorTorqueNm: 45,
    motorType: '500W Hub (Generic)',
    bikeClass: 'class-1',
    batteryWh: 614,
    weightLbs: 168,
    maxSystemWeightLbs: 600,
    salesModel: 'direct-to-consumer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Pet Cargo Trike' }],
  },
  {
    name: 'Bunch Bikes The Preschool 4+',
    slug: 'bunch-bikes-the-preschool-4',
    brand: 'bunch-bikes',
    category: 'cargo-bike',
    price: 8277,
    affiliateUrl: 'https://www.bunchbike.com/products/the-preschool-4-upgraded-electric-cargo-bike-for-up-to-6-kids',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'front-box',
    motorBrand: 'Generic',
    motorPosition: 'hub-rear',
    motorNominalWatts: 500,
    motorTorqueNm: 45,
    motorType: '500W Hub (Generic)',
    bikeClass: 'class-1',
    batteryWh: 614,
    weightLbs: 175,
    maxSystemWeightLbs: 600,
    salesModel: 'direct-to-consumer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Commercial/School Trike' }],
  },
  {
    name: 'Butchers & Bicycles MK1-E',
    slug: 'butchers-and-bicycles-mk1-e',
    brand: 'butchers-and-bicycles',
    category: 'cargo-bike',
    price: 9000,
    affiliateUrl: 'https://www.butchersandbicycles.com',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'trike',
    motorBrand: 'Bosch',
    motorPosition: 'mid-drive',
    motorNominalWatts: 250,
    motorTorqueNm: 85,
    motorType: 'Performance CX Gen4 (Bosch)',
    bikeClass: 'class-1',
    batteryWh: 500,
    weightLbs: 110,
    maxSystemWeightLbs: 551,
    salesModel: 'dealer',
    availableIn: 'Residual Stock',
    bestFor: [{ tag: 'Premium Tilting Trike' }],
  },
  {
    name: 'Buzz Bicycles Beekeeper',
    slug: 'buzz-bicycles-beekeeper',
    brand: 'buzz-bicycles',
    category: 'cargo-bike',
    price: 1299,
    affiliateUrl: 'https://www.buzzbicycles.com/buzz-beekeeper-electric-cargo-bike-e4023/',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'longtail',
    motorBrand: 'Generic',
    motorPosition: 'hub-rear',
    motorNominalWatts: 500,
    motorTorqueNm: 60,
    motorType: '500W Hub (Generic)',
    bikeClass: 'class-2',
    batteryWh: 500,
    weightLbs: 72,
    maxSystemWeightLbs: 400,
    salesModel: 'direct-to-consumer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Budget Longtail' }],
  },
  {
    name: 'Cannondale Cargowagen Neo 2',
    slug: 'cannondale-cargowagen-neo-2',
    brand: 'cannondale',
    category: 'cargo-bike',
    price: 4300,
    affiliateUrl: 'https://www.cannondale.com/en-us/bikes/electric/e-cargo/cargowagen-neo',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'longtail',
    motorBrand: 'Bosch',
    motorPosition: 'mid-drive',
    motorNominalWatts: 250,
    motorTorqueNm: 85,
    motorType: 'Cargo Line (Bosch)',
    bikeClass: 'class-1',
    batteryWh: 545,
    weightLbs: 77,
    maxSystemWeightLbs: 441,
    salesModel: 'dealer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Premium Longtail' }],
  },
  {
    name: 'Cannondale Cargowagen Neo 1',
    slug: 'cannondale-cargowagen-neo-1',
    brand: 'cannondale',
    category: 'cargo-bike',
    price: 5500,
    affiliateUrl: 'https://www.cannondale.com/en-us/bikes/electric/e-cargo/cargowagen-neo',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'longtail',
    motorBrand: 'Bosch',
    motorPosition: 'mid-drive',
    motorNominalWatts: 250,
    motorTorqueNm: 85,
    motorType: 'Performance Speed (Bosch)',
    bikeClass: 'class-3',
    batteryWh: 725,
    weightLbs: 78,
    maxSystemWeightLbs: 441,
    salesModel: 'dealer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Premium Longtail' }],
  },
  {
    name: 'Carqon Cruise Smart',
    slug: 'carqon-cruise-smart',
    brand: 'carqon',
    category: 'cargo-bike',
    price: 9999,
    affiliateUrl: 'https://www.carqon.com/us/carqon-cruise-smart',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'front-box',
    motorBrand: 'Bosch',
    motorPosition: 'mid-drive',
    motorNominalWatts: 250,
    motorTorqueNm: 85,
    motorType: 'CX Cargo Line (Bosch)',
    bikeClass: 'class-1',
    batteryWh: 400,
    dualBatteryCapable: true,
    dualBatteryWh: 1000,
    weightLbs: 143,
    maxSystemWeightLbs: 396,
    salesModel: 'dealer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Premium Front-loader' }],
  },
  {
    name: 'CERO Bikes CERO One',
    slug: 'cero-bikes-cero-one',
    brand: 'cero-bikes',
    category: 'cargo-bike',
    price: 3799,
    affiliateUrl: 'https://www.cerobicycles.com',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'midtail',
    motorBrand: 'Shimano',
    motorNominalWatts: 250,
    motorType: 'STEPS (Shimano)',
    bikeClass: 'class-1',
    salesModel: 'direct-to-consumer',
    availableIn: 'Limited',
    bestFor: [{ tag: 'Mid-Range Midtail' }],
  },
  {
    name: 'Christiania Bikes Classic / Model T',
    slug: 'christiania-bikes-classic-model-t',
    brand: 'christiania-bikes',
    category: 'cargo-bike',
    price: 3000,
    affiliateUrl: 'https://www.christianiabikesamerica.com',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'front-box',
    motorBrand: 'Optional',
    motorType: 'Various (Optional)',
    salesModel: 'dealer',
    availableIn: 'Limited',
    bestFor: [{ tag: 'European Front-loader Trike' }],
  },
  {
    name: 'Coaster Cycles Venture',
    slug: 'coaster-cycles-venture',
    brand: 'coaster-cycles',
    category: 'cargo-bike',
    price: 7250,
    affiliateUrl: 'https://www.coastercycles.com',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'trike',
    motorBrand: 'Bosch',
    motorPosition: 'mid-drive',
    motorNominalWatts: 250,
    motorType: 'Performance (Bosch)',
    bikeClass: 'class-1',
    maxSystemWeightLbs: 400,
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Commercial Trike' }],
  },
  {
    name: 'Coaster Cycles Freighter',
    slug: 'coaster-cycles-freighter',
    brand: 'coaster-cycles',
    category: 'cargo-bike',
    price: 8500,
    affiliateUrl: 'https://www.coastercycles.com',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'trike',
    motorBrand: 'Bosch',
    motorPosition: 'mid-drive',
    motorNominalWatts: 250,
    motorType: 'Cargo Line (Bosch)',
    bikeClass: 'class-1',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Commercial Trike' }],
  },
  {
    name: 'ENGWE LE20',
    slug: 'engwe-le20',
    brand: 'engwe',
    category: 'cargo-bike',
    price: 1499,
    affiliateUrl: 'https://us.engwe.com/products/le20',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'longtail',
    motorBrand: 'Generic',
    motorPosition: 'hub-rear',
    motorNominalWatts: 750,
    motorPeakWatts: 1300,
    motorTorqueNm: 75,
    motorType: '750W Hub (Generic)',
    bikeClass: 'class-2',
    batteryWh: 922,
    dualBatteryCapable: true,
    dualBatteryWh: 1843,
    maxSystemWeightLbs: 440,
    salesModel: 'direct-to-consumer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Budget Longtail' }],
  },
  {
    name: 'Ferla Royce MAX (Mid-Drive)',
    slug: 'ferla-royce-max-mid-drive',
    brand: 'ferla',
    category: 'cargo-bike',
    price: 7499,
    affiliateUrl: 'https://www.ferlafamilybikes.com/products/ferla-cargo-bike-royce-mid-drive',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'front-box',
    motorBrand: 'Bafang',
    motorPosition: 'mid-drive',
    motorNominalWatts: 750,
    motorTorqueNm: 160,
    motorType: '750W Mid-drive (Bafang)',
    bikeClass: 'class-2',
    batteryWh: 840,
    weightLbs: 160,
    maxSystemWeightLbs: 600,
    salesModel: 'direct-to-consumer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Family Front-loader Trike' }],
  },
  {
    name: 'Ferla Royce II',
    slug: 'ferla-royce-ii',
    brand: 'ferla',
    category: 'cargo-bike',
    price: 5499,
    affiliateUrl: 'https://www.ferlafamilybikes.com/products/ferla-cargo-bike-royce',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'front-box',
    motorBrand: 'Bafang',
    motorPosition: 'hub-rear',
    motorNominalWatts: 750,
    motorType: '750W Hub (Bafang)',
    bikeClass: 'class-2',
    batteryWh: 840,
    weightLbs: 158,
    maxSystemWeightLbs: 700,
    salesModel: 'direct-to-consumer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Family Front-loader Trike' }],
  },
  {
    name: 'Ferla Lagom',
    slug: 'ferla-lagom',
    brand: 'ferla',
    category: 'cargo-bike',
    price: 3499,
    affiliateUrl: 'https://www.ferlafamilybikes.com/products/ferla-cargo-bike-longtail',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'longtail',
    motorBrand: 'Generic',
    motorPosition: 'hub-rear',
    motorNominalWatts: 500,
    motorType: '500W Hub (Generic)',
    bikeClass: 'class-2',
    dualBatteryCapable: true,
    weightLbs: 65,
    maxSystemWeightLbs: 440,
    salesModel: 'direct-to-consumer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Mid-Range Longtail' }],
  },
  {
    name: 'Fernhay eQuad',
    slug: 'fernhay-equad',
    brand: 'fernhay',
    category: 'cargo-bike',
    price: 0,
    affiliateUrl: 'https://fernhay.com',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'trike',
    motorBrand: 'Generic',
    motorNominalWatts: 250,
    motorType: '250W (Generic)',
    bikeClass: 'class-1',
    batteryWh: 2300,
    maxSystemWeightLbs: 440,
    availableIn: 'In Stock (Fleet)',
    bestFor: [{ tag: '4-Wheel Quad' }],
  },
  {
    name: 'Fiido T2',
    slug: 'fiido-t2',
    brand: 'fiido',
    category: 'cargo-bike',
    price: 1499,
    affiliateUrl: 'https://www.fiido.com/products/fiido-t2-longtail-cargo-ebike',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'longtail',
    motorBrand: 'Generic',
    motorPosition: 'hub-rear',
    motorNominalWatts: 750,
    motorTorqueNm: 60,
    motorType: '750W Hub (Generic)',
    bikeClass: 'class-2',
    batteryWh: 998,
    weightLbs: 87,
    maxSystemWeightLbs: 440,
    salesModel: 'direct-to-consumer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Budget Longtail' }],
  },
  {
    name: 'GoCycle CXi',
    slug: 'gocycle-cxi',
    brand: 'gocycle',
    category: 'cargo-bike',
    price: 6999,
    affiliateUrl: 'https://gocycle.com/us/webstore/gocycles/gocycle-fc/gocycle-cxi/',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'compact',
    motorBrand: 'Proprietary',
    motorPosition: 'hub-rear',
    motorNominalWatts: 500,
    motorType: '500W Front Hub (Proprietary)',
    bikeClass: 'class-1',
    batteryWh: 375,
    weightLbs: 50,
    salesModel: 'direct-to-consumer',
    availableIn: 'Limited',
    bestFor: [{ tag: 'Premium Folding Cargo' }],
  },
  {
    name: 'GoCycle CX+',
    slug: 'gocycle-cx',
    brand: 'gocycle',
    category: 'cargo-bike',
    price: 7999,
    affiliateUrl: 'https://gocycle.com/us/webstore/gocycles/gocycle-fc/gocycle-cxplus/',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'compact',
    motorBrand: 'Proprietary',
    motorPosition: 'hub-rear',
    motorNominalWatts: 500,
    motorType: '500W Front Hub (Proprietary)',
    bikeClass: 'class-1',
    batteryWh: 375,
    weightLbs: 51,
    salesModel: 'direct-to-consumer',
    availableIn: 'Limited',
    bestFor: [{ tag: 'Premium Folding Cargo' }],
  },
  {
    name: 'Heybike Hauler',
    slug: 'heybike-hauler',
    brand: 'heybike',
    category: 'cargo-bike',
    price: 1399,
    affiliateUrl: 'https://www.heybike.com/products/hauler',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'longtail',
    motorBrand: 'Generic',
    motorPosition: 'hub-rear',
    motorNominalWatts: 750,
    motorType: '750W Hub (Generic)',
    bikeClass: 'class-2',
    batteryWh: 732,
    dualBatteryCapable: true,
    dualBatteryWh: 1464,
    maxSystemWeightLbs: 440,
    salesModel: 'direct-to-consumer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Budget Longtail' }],
  },
  {
    name: 'Himiway Big Dog',
    slug: 'himiway-big-dog',
    brand: 'himiway',
    category: 'cargo-bike',
    price: 1999,
    affiliateUrl: 'https://himiwaybike.com/products/big-dog',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'compact',
    motorBrand: 'Generic',
    motorPosition: 'hub-rear',
    motorNominalWatts: 750,
    motorTorqueNm: 86,
    motorType: '750W Hub (Generic)',
    bikeClass: 'class-2',
    batteryWh: 960,
    weightLbs: 88,
    maxSystemWeightLbs: 400,
    salesModel: 'direct-to-consumer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Budget Compact' }],
  },
  {
    name: 'Honda Fastport eQuad (Large)',
    slug: 'honda-fastport-equad-large',
    brand: 'honda',
    category: 'cargo-bike',
    price: 20000,
    affiliateUrl: 'https://fastport.honda.com',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'trike',
    motorBrand: 'Honda',
    motorType: 'Pedal-by-wire (Honda)',
    batteryWh: 2600,
    dualBatteryCapable: true,
    weightLbs: 400,
    maxSystemWeightLbs: 650,
    availableIn: 'Summer 2026',
    bestFor: [{ tag: '4-Wheel Quad' }],
  },
  {
    name: 'Honda Fastport eQuad (Small)',
    slug: 'honda-fastport-equad-small',
    brand: 'honda',
    category: 'cargo-bike',
    price: 0,
    affiliateUrl: 'https://fastport.honda.com',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'trike',
    motorBrand: 'Honda',
    motorType: 'Pedal-by-wire (Honda)',
    batteryWh: 2600,
    dualBatteryCapable: true,
    maxSystemWeightLbs: 320,
    availableIn: 'Summer 2026',
    bestFor: [{ tag: '4-Wheel Quad' }],
  },
  {
    name: 'Icicle Tricycles Custom Cargo Trike',
    slug: 'icicle-tricycles-custom-cargo-trike',
    brand: 'icicle-tricycles',
    category: 'cargo-bike',
    price: 0,
    affiliateUrl: 'https://icetrikes.com',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'trike',
    motorBrand: 'Optional',
    motorType: 'Various (Optional)',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Commercial Trike' }],
  },
  {
    name: 'KBO Ranger',
    slug: 'kbo-ranger',
    brand: 'kbo',
    category: 'cargo-bike',
    price: 1799,
    affiliateUrl: 'https://www.kbobike.com/products/electric-cargo-bike-ranger',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'longtail',
    motorBrand: 'Generic',
    motorPosition: 'hub-rear',
    motorNominalWatts: 750,
    motorType: '750W Geared Hub (Generic)',
    bikeClass: 'class-2',
    batteryWh: 840,
    weightLbs: 77,
    maxSystemWeightLbs: 400,
    salesModel: 'direct-to-consumer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Budget Longtail' }],
  },
  {
    name: 'Larry vs Harry Original Bullitt',
    slug: 'larry-vs-harry-original-bullitt',
    brand: 'larry-vs-harry',
    category: 'cargo-bike',
    price: 5100,
    affiliateUrl: 'https://www.larryvsharry.com/products/original-bullitt',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'front-box',
    weightLbs: 49,
    maxSystemWeightLbs: 397,
    salesModel: 'dealer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Premium Front-loader' }],
  },
  {
    name: 'Larry vs Harry eBullitt',
    slug: 'larry-vs-harry-ebullitt',
    brand: 'larry-vs-harry',
    category: 'cargo-bike',
    price: 5700,
    affiliateUrl: 'https://www.larryvsharry.com/products/ebullitt-6100',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'front-box',
    motorBrand: 'Shimano',
    motorNominalWatts: 250,
    motorTorqueNm: 60,
    motorType: 'STEPS 6100 / EP600 / EP801 (Shimano)',
    bikeClass: 'class-1',
    batteryWh: 418,
    weightLbs: 62,
    maxSystemWeightLbs: 397,
    salesModel: 'dealer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Premium Front-loader' }],
  },
  {
    name: 'Lectric XPedition 2.0',
    slug: 'lectric-xpedition-2-0',
    brand: 'lectric',
    category: 'cargo-bike',
    price: 1399,
    affiliateUrl: 'https://lectricebikes.com/products/xpedition-single-battery',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'longtail',
    motorBrand: 'Generic',
    motorPosition: 'hub-rear',
    motorNominalWatts: 750,
    motorPeakWatts: 1310,
    motorType: '750W Hub (Generic)',
    bikeClass: 'class-2',
    batteryWh: 624,
    dualBatteryCapable: true,
    dualBatteryWh: 1680,
    weightLbs: 76,
    maxSystemWeightLbs: 450,
    salesModel: 'direct-to-consumer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Budget Longtail' }],
  },
  {
    name: 'Madsen Electric DK2',
    slug: 'madsen-electric-dk2',
    brand: 'madsen',
    category: 'cargo-bike',
    price: 3799,
    affiliateUrl: 'https://www.madsencycles.com/products/electric-dk2-copy',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'longtail',
    motorBrand: 'Bafang',
    motorPosition: 'mid-drive',
    motorNominalWatts: 750,
    motorTorqueNm: 120,
    motorType: '750W Mid-drive (Bafang)',
    bikeClass: 'class-2',
    batteryWh: 780,
    weightLbs: 90,
    maxSystemWeightLbs: 600,
    salesModel: 'direct-to-consumer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Family Bucket Bike' }],
  },
  {
    name: 'Madsen DK2 (Non-Electric)',
    slug: 'madsen-dk2-non-electric',
    brand: 'madsen',
    category: 'cargo-bike',
    price: 2299,
    affiliateUrl: 'https://www.madsencycles.com/collections/dk2-bikes',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'longtail',
    weightLbs: 58,
    maxSystemWeightLbs: 600,
    salesModel: 'direct-to-consumer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Non-Electric Bucket' }],
  },
  {
    name: 'Magnum Payload',
    slug: 'magnum-payload',
    brand: 'magnum',
    category: 'cargo-bike',
    price: 1699,
    affiliateUrl: 'https://magnumbikes.com/products/magnum-payload',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'longtail',
    motorBrand: 'Generic',
    motorPosition: 'hub-rear',
    motorNominalWatts: 750,
    motorType: '500W/750W Hub (Generic)',
    bikeClass: 'class-1',
    batteryWh: 1008,
    maxSystemWeightLbs: 400,
    salesModel: 'direct-to-consumer',
    availableIn: 'Out of Stock',
    bestFor: [{ tag: 'Budget Longtail' }],
  },
  {
    name: 'MOD Bikes Cargo 3',
    slug: 'mod-bikes-cargo-3',
    brand: 'mod-bikes',
    category: 'cargo-bike',
    price: 2199,
    affiliateUrl: 'https://mod-bikes.com/products/mod-cargo-3',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'longtail',
    motorBrand: 'Generic',
    motorPosition: 'hub-rear',
    motorType: 'Rear Hub + Torque Sensor (Generic)',
    bikeClass: 'class-2',
    dualBatteryCapable: true,
    weightLbs: 75,
    maxSystemWeightLbs: 400,
    salesModel: 'direct-to-consumer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Mid-Range Longtail' }],
  },
  {
    name: 'Mokwheel Scoria',
    slug: 'mokwheel-scoria',
    brand: 'mokwheel',
    category: 'cargo-bike',
    price: 1299,
    affiliateUrl: 'https://www.mokwheel.com/products/scoria',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'compact',
    motorBrand: 'Generic',
    motorPosition: 'hub-rear',
    motorNominalWatts: 750,
    motorType: '750W Hub (Generic)',
    bikeClass: 'class-2',
    salesModel: 'direct-to-consumer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Budget Utility' }],
  },
  {
    name: 'Momentum Cito E+',
    slug: 'momentum-cito-e',
    brand: 'momentum',
    category: 'cargo-bike',
    price: 3200,
    affiliateUrl: 'https://www.momentum-biking.com/us/cito-eplus',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'longtail',
    motorBrand: 'Giant',
    motorPosition: 'hub-rear',
    motorNominalWatts: 750,
    motorTorqueNm: 80,
    motorType: 'SyncDrive Move S 750W Hub (Giant)',
    bikeClass: 'class-2',
    batteryWh: 780,
    weightLbs: 75,
    maxSystemWeightLbs: 408,
    salesModel: 'dealer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Mid-Range Longtail' }],
  },
  {
    name: 'Mongoose Envoy',
    slug: 'mongoose-envoy',
    brand: 'mongoose',
    category: 'cargo-bike',
    price: 699,
    affiliateUrl: 'https://www.mongoose.com/products/envoy',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'longtail',
    weightLbs: 40,
    maxSystemWeightLbs: 300,
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Non-Electric Budget Longtail' }],
  },
  {
    name: 'Mubea PACK',
    slug: 'mubea-pack',
    brand: 'mubea',
    category: 'cargo-bike',
    price: 16170,
    affiliateUrl: 'https://us.mubea-umobility.com/',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'trike',
    motorBrand: 'Proprietary',
    motorNominalWatts: 250,
    motorType: '250W Chainless Serial (Proprietary)',
    bikeClass: 'class-1',
    batteryWh: 2880,
    dualBatteryCapable: true,
    maxSystemWeightLbs: 551,
    cargoCapacityLbs: 551,
    availableIn: 'In Stock (Fleet)',
    bestFor: [{ tag: '4-Wheel Quad' }],
  },
  {
    name: 'Mubea WORK',
    slug: 'mubea-work',
    brand: 'mubea',
    category: 'cargo-bike',
    price: 18970,
    affiliateUrl: 'https://www.mubea-umobility.com/en/products/work',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'trike',
    motorBrand: 'Proprietary',
    motorNominalWatts: 250,
    motorType: '250W Chainless Serial (Proprietary)',
    bikeClass: 'class-1',
    batteryWh: 2880,
    dualBatteryCapable: true,
    maxSystemWeightLbs: 441,
    availableIn: 'In Stock (Fleet)',
    bestFor: [{ tag: '4-Wheel Quad' }],
  },
  {
    name: 'Nihola Family / 4.0 / Dog / Flex',
    slug: 'nihola-family-4-0-dog-flex',
    brand: 'nihola',
    category: 'cargo-bike',
    price: 3500,
    affiliateUrl: 'https://nihola.com',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'front-box',
    motorBrand: 'Optional',
    motorType: 'Various (Optional)',
    salesModel: 'dealer',
    availableIn: 'Limited',
    bestFor: [{ tag: 'European Front-loader Trike' }],
  },
  {
    name: 'Omnium Cargo Cargo V3 / Mini-Max / E-Cargo',
    slug: 'omnium-cargo-cargo-v3-mini-max-e-cargo',
    brand: 'omnium-cargo',
    category: 'cargo-bike',
    price: 2100,
    affiliateUrl: 'https://omniumcargo.us',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'front-box',
    motorBrand: 'Various',
    motorType: 'Various (Various)',
    salesModel: 'direct-to-consumer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Mid-Range Front-loader' }],
  },
  {
    name: 'Pedego Stretch',
    slug: 'pedego-stretch',
    brand: 'pedego',
    category: 'cargo-bike',
    price: 3495,
    affiliateUrl: 'https://www.pedegoelectricbikes.com/products/stretch',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'longtail',
    motorBrand: 'Generic',
    motorPosition: 'hub-rear',
    motorNominalWatts: 500,
    motorTorqueNm: 45,
    motorType: '500W Hub (Generic)',
    bikeClass: 'class-1',
    batteryWh: 624,
    weightLbs: 65,
    maxSystemWeightLbs: 400,
    salesModel: 'dealer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Mid-Range Longtail' }],
  },
  {
    name: 'Rad Power Bikes RadWagon 5',
    slug: 'rad-power-bikes-radwagon-5',
    brand: 'rad-power-bikes',
    category: 'cargo-bike',
    price: 2399,
    affiliateUrl: 'https://www.radpowerbikes.com/products/radwagon-electric-cargo-bike',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'longtail',
    motorBrand: 'Proprietary',
    motorPosition: 'hub-rear',
    motorNominalWatts: 750,
    motorTorqueNm: 90,
    motorType: '750W Hub (Proprietary)',
    bikeClass: 'class-2',
    batteryWh: 720,
    weightLbs: 86,
    maxSystemWeightLbs: 375,
    salesModel: 'direct-to-consumer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Mid-Range Longtail' }],
  },
  {
    name: 'Radio Flyer Flyer Via',
    slug: 'radio-flyer-flyer-via',
    brand: 'radio-flyer',
    category: 'cargo-bike',
    price: 2299,
    affiliateUrl: 'https://www.radioflyer.com/products/flyer-via',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'midtail',
    motorBrand: 'Proprietary',
    motorPosition: 'hub-rear',
    motorNominalWatts: 500,
    motorType: '500W Flight Speed Hub (Proprietary)',
    bikeClass: 'class-2',
    batteryWh: 480,
    weightLbs: 65,
    maxSystemWeightLbs: 400,
    salesModel: 'direct-to-consumer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Mid-Range Midtail' }],
  },
  {
    name: 'Radio Flyer Flyer Via Pro',
    slug: 'radio-flyer-flyer-via-pro',
    brand: 'radio-flyer',
    category: 'cargo-bike',
    price: 2999,
    affiliateUrl: 'https://www.radioflyer.com/products/flyer-via-pro',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'midtail',
    motorBrand: 'Proprietary',
    motorPosition: 'hub-rear',
    motorNominalWatts: 750,
    motorType: '750W Flight Speed Hub (Proprietary)',
    bikeClass: 'class-2',
    batteryWh: 580,
    weightLbs: 73,
    maxSystemWeightLbs: 400,
    salesModel: 'direct-to-consumer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Mid-Range Midtail' }],
  },
  {
    name: 'Ride1Up Vorsa',
    slug: 'ride1up-vorsa',
    brand: 'ride1up',
    category: 'cargo-bike',
    price: 1495,
    affiliateUrl: 'https://ride1up.com/product/vorsa/',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'longtail',
    motorBrand: 'Generic',
    motorPosition: 'hub-rear',
    motorNominalWatts: 750,
    motorType: '750W Hub (Generic)',
    bikeClass: 'class-2',
    salesModel: 'direct-to-consumer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Budget Longtail' }],
  },
  {
    name: 'Riese & Müller Load5 60',
    slug: 'riese-and-muller-load5-60',
    brand: 'riese-and-muller',
    category: 'cargo-bike',
    price: 11669,
    affiliateUrl: 'https://www.r-m.de/en-us/bikes/load5-60/',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'front-box',
    motorBrand: 'Bosch',
    motorPosition: 'mid-drive',
    motorNominalWatts: 250,
    motorTorqueNm: 100,
    motorType: 'Cargo Line / Perf Speed (Bosch)',
    bikeClass: 'class-1',
    batteryWh: 725,
    dualBatteryCapable: true,
    dualBatteryWh: 1600,
    weightLbs: 78,
    maxSystemWeightLbs: 441,
    salesModel: 'dealer',
    availableIn: 'Built to Order',
    bestFor: [{ tag: 'Premium Front-loader' }],
  },
  {
    name: 'Riese & Müller Load5 75',
    slug: 'riese-and-muller-load5-75',
    brand: 'riese-and-muller',
    category: 'cargo-bike',
    price: 11929,
    affiliateUrl: 'https://www.r-m.de/en-us/bikes/load5-75/',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'front-box',
    motorBrand: 'Bosch',
    motorPosition: 'mid-drive',
    motorNominalWatts: 250,
    motorTorqueNm: 100,
    motorType: 'Cargo Line / Perf Speed (Bosch)',
    bikeClass: 'class-1',
    batteryWh: 725,
    dualBatteryCapable: true,
    dualBatteryWh: 1600,
    weightLbs: 78,
    maxSystemWeightLbs: 441,
    salesModel: 'dealer',
    availableIn: 'Built to Order',
    bestFor: [{ tag: 'Premium Front-loader' }],
  },
  {
    name: 'Riese & Müller Packster2 70',
    slug: 'riese-and-muller-packster2-70',
    brand: 'riese-and-muller',
    category: 'cargo-bike',
    price: 10719,
    affiliateUrl: 'https://www.r-m.de/en-us/bikes/packster2-70/',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'front-box',
    motorBrand: 'Bosch',
    motorPosition: 'mid-drive',
    motorNominalWatts: 250,
    motorType: 'Cargo Line (Bosch)',
    bikeClass: 'class-1',
    batteryWh: 625,
    dualBatteryCapable: true,
    dualBatteryWh: 1500,
    weightLbs: 88,
    maxSystemWeightLbs: 441,
    salesModel: 'dealer',
    availableIn: 'Built to Order',
    bestFor: [{ tag: 'Premium Front-loader' }],
  },
  {
    name: 'Riese & Müller Packster2 70 CT',
    slug: 'riese-and-muller-packster2-70-ct',
    brand: 'riese-and-muller',
    category: 'cargo-bike',
    price: 12000,
    affiliateUrl: 'https://www.r-m.de/en-us/bikes/packster2-70-ct/',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'front-box',
    motorBrand: 'Bosch',
    motorPosition: 'mid-drive',
    motorNominalWatts: 250,
    motorType: 'Cargo Line (Bosch)',
    bikeClass: 'class-1',
    batteryWh: 750,
    dualBatteryCapable: true,
    dualBatteryWh: 1500,
    weightLbs: 95,
    maxSystemWeightLbs: 441,
    salesModel: 'dealer',
    availableIn: 'Built to Order',
    bestFor: [{ tag: 'Premium Front-loader' }],
  },
  {
    name: 'Riese & Müller Transporter2 85',
    slug: 'riese-and-muller-transporter2-85',
    brand: 'riese-and-muller',
    category: 'cargo-bike',
    price: 9119,
    affiliateUrl: 'https://www.r-m.de/en-us/bikes/transporter2-85/',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'front-box',
    motorBrand: 'Bosch',
    motorPosition: 'mid-drive',
    motorNominalWatts: 250,
    motorType: 'Performance Line (Bosch)',
    bikeClass: 'class-1',
    batteryWh: 545,
    dualBatteryCapable: true,
    dualBatteryWh: 1450,
    weightLbs: 108,
    maxSystemWeightLbs: 485,
    salesModel: 'dealer',
    availableIn: 'Built to Order',
    bestFor: [{ tag: 'Premium Front-loader Platform' }],
  },
  {
    name: 'Riese & Müller Transporter2 65',
    slug: 'riese-and-muller-transporter2-65',
    brand: 'riese-and-muller',
    category: 'cargo-bike',
    price: 8879,
    affiliateUrl: 'https://www.r-m.de/en-us/bikes/transporter2-65/',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'front-box',
    motorBrand: 'Bosch',
    motorPosition: 'mid-drive',
    motorNominalWatts: 250,
    motorType: 'Performance Line (Bosch)',
    bikeClass: 'class-1',
    batteryWh: 545,
    dualBatteryCapable: true,
    dualBatteryWh: 725,
    weightLbs: 101,
    maxSystemWeightLbs: 485,
    salesModel: 'dealer',
    availableIn: 'Built to Order',
    bestFor: [{ tag: 'Premium Front-loader Platform' }],
  },
  {
    name: 'Riese & Müller Carrie2',
    slug: 'riese-and-muller-carrie2',
    brand: 'riese-and-muller',
    category: 'cargo-bike',
    price: 9500,
    affiliateUrl: 'https://www.r-m.de/en-us/bikes/carrie2/',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'front-box',
    motorBrand: 'Bosch',
    motorPosition: 'mid-drive',
    motorNominalWatts: 250,
    motorTorqueNm: 90,
    motorType: 'Performance Line PX (Bosch)',
    bikeClass: 'class-1',
    batteryWh: 545,
    weightLbs: 78,
    maxSystemWeightLbs: 441,
    salesModel: 'dealer',
    availableIn: 'Built to Order',
    bestFor: [{ tag: 'Premium Compact Front-loader' }],
  },
  {
    name: 'Riese & Müller Multitinker2',
    slug: 'riese-and-muller-multitinker2',
    brand: 'riese-and-muller',
    category: 'cargo-bike',
    price: 8259,
    affiliateUrl: 'https://www.r-m.de/en-us/bikes/multitinker2/',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'longtail',
    motorBrand: 'Bosch',
    motorPosition: 'mid-drive',
    motorNominalWatts: 250,
    motorTorqueNm: 95,
    motorType: 'Cargo Line / Perf Sport (Bosch)',
    bikeClass: 'class-1',
    batteryWh: 625,
    weightLbs: 77,
    maxSystemWeightLbs: 441,
    salesModel: 'dealer',
    availableIn: 'Built to Order',
    bestFor: [{ tag: 'Premium Longtail' }],
  },
  {
    name: 'Riese & Müller Multicharger2',
    slug: 'riese-and-muller-multicharger2',
    brand: 'riese-and-muller',
    category: 'cargo-bike',
    price: 7189,
    affiliateUrl: 'https://www.r-m.de/en-us/bikes/multicharger2/',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'longtail',
    motorBrand: 'Bosch',
    motorPosition: 'mid-drive',
    motorNominalWatts: 250,
    motorTorqueNm: 85,
    motorType: 'Performance CX (Bosch)',
    bikeClass: 'class-1',
    batteryWh: 625,
    salesModel: 'dealer',
    availableIn: 'Built to Order',
    bestFor: [{ tag: 'Premium Longtail' }],
  },
  {
    name: 'Rytle MovR3',
    slug: 'rytle-movr3',
    brand: 'rytle',
    category: 'cargo-bike',
    price: 16000,
    affiliateUrl: 'https://rytle.com',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'trike',
    motorBrand: 'Heinzmann',
    motorPosition: 'hub-rear',
    motorNominalWatts: 250,
    motorTorqueNm: 113,
    motorType: '2x125W Hub (Heinzmann)',
    bikeClass: 'class-1',
    batteryWh: 1584,
    maxSystemWeightLbs: 815,
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Commercial Trike' }],
  },
  {
    name: 'Specialized Globe Haul ST',
    slug: 'specialized-globe-haul-st',
    brand: 'specialized',
    category: 'cargo-bike',
    price: 2700,
    affiliateUrl: 'https://www.specialized.com/us/en/globe-haul-st/p/277759',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'midtail',
    motorBrand: 'Proprietary',
    motorPosition: 'hub-rear',
    motorNominalWatts: 700,
    motorType: 'Globe Cargo Drive 700W Hub (Proprietary)',
    bikeClass: 'class-1',
    batteryWh: 772,
    weightLbs: 81,
    maxSystemWeightLbs: 419,
    salesModel: 'dealer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Mid-Range Midtail' }],
  },
  {
    name: 'Specialized Globe Haul LT',
    slug: 'specialized-globe-haul-lt',
    brand: 'specialized',
    category: 'cargo-bike',
    price: 3500,
    affiliateUrl: 'https://www.specialized.com/us/en/globe-haul-lt/p/277758',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'longtail',
    motorBrand: 'Proprietary',
    motorPosition: 'hub-rear',
    motorNominalWatts: 700,
    motorType: 'Globe Cargo Drive 700W Hub (Proprietary)',
    bikeClass: 'class-1',
    batteryWh: 772,
    weightLbs: 88,
    maxSystemWeightLbs: 441,
    salesModel: 'dealer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Mid-Range Longtail' }],
  },
  {
    name: 'Surface 604 Werk',
    slug: 'surface-604-werk',
    brand: 'surface-604',
    category: 'cargo-bike',
    price: 2199,
    affiliateUrl: 'https://surface604bikes.com',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'longtail',
    motorBrand: 'Generic',
    motorPosition: 'hub-rear',
    motorNominalWatts: 750,
    motorType: '500W/750W Hub (Generic)',
    bikeClass: 'class-2',
    batteryWh: 960,
    salesModel: 'direct-to-consumer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Mid-Range Utility' }],
  },
  {
    name: 'Surly Big Easy',
    slug: 'surly-big-easy',
    brand: 'surly',
    category: 'cargo-bike',
    price: 5000,
    affiliateUrl: 'https://surlybikes.com/products/big-easy',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'longtail',
    motorBrand: 'Bosch',
    motorPosition: 'mid-drive',
    motorNominalWatts: 250,
    motorType: 'Cargo Line (Bosch)',
    bikeClass: 'class-1',
    batteryWh: 725,
    weightLbs: 65,
    maxSystemWeightLbs: 400,
    salesModel: 'dealer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Premium Longtail' }],
  },
  {
    name: 'Surly Big Dummy',
    slug: 'surly-big-dummy',
    brand: 'surly',
    category: 'cargo-bike',
    price: 2449,
    affiliateUrl: 'https://surlybikes.com/collections/big-dummy',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'longtail',
    weightLbs: 42,
    maxSystemWeightLbs: 400,
    salesModel: 'dealer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Non-Electric Longtail' }],
  },
  {
    name: 'Tenways Cargo One',
    slug: 'tenways-cargo-one',
    brand: 'tenways',
    category: 'cargo-bike',
    price: 5499,
    affiliateUrl: 'https://us.tenways.com/products/cargo-one',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'front-box',
    motorBrand: 'Bafang',
    motorNominalWatts: 250,
    motorTorqueNm: 100,
    motorType: 'M600 (Bafang)',
    bikeClass: 'class-1',
    batteryWh: 960,
    salesModel: 'dealer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Mid-Range Front-loader' }],
  },
  {
    name: 'Tern GSD Gen 3',
    slug: 'tern-gsd-gen-3',
    brand: 'tern',
    category: 'cargo-bike',
    price: 5799,
    affiliateUrl: 'https://store.ternbicycles.com/products/gsd-p10-gen-3',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'longtail',
    motorBrand: 'Bosch',
    motorPosition: 'mid-drive',
    motorNominalWatts: 250,
    motorTorqueNm: 85,
    motorType: 'Cargo Line / Smart Sys (Bosch)',
    bikeClass: 'class-1',
    batteryWh: 500,
    dualBatteryCapable: true,
    dualBatteryWh: 800,
    weightLbs: 75,
    maxSystemWeightLbs: 463,
    salesModel: 'dealer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Premium Longtail' }],
  },
  {
    name: 'Tern HSD Gen 2',
    slug: 'tern-hsd-gen-2',
    brand: 'tern',
    category: 'cargo-bike',
    price: 4499,
    affiliateUrl: 'https://store.ternbicycles.com/products/hsd-p10-gen-2',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'midtail',
    motorBrand: 'Bosch',
    motorPosition: 'mid-drive',
    motorNominalWatts: 250,
    motorTorqueNm: 75,
    motorType: 'Performance Line / Speed (Bosch)',
    bikeClass: 'class-1',
    batteryWh: 545,
    weightLbs: 55,
    maxSystemWeightLbs: 397,
    salesModel: 'dealer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Premium Compact Midtail' }],
  },
  {
    name: 'Tern Quick Haul',
    slug: 'tern-quick-haul',
    brand: 'tern',
    category: 'cargo-bike',
    price: 2999,
    affiliateUrl: 'https://store.ternbicycles.com/products/quick-haul-d8',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'compact',
    motorBrand: 'Bosch',
    motorPosition: 'mid-drive',
    motorNominalWatts: 250,
    motorTorqueNm: 50,
    motorType: 'Active Plus / Perf Sport (Bosch)',
    bikeClass: 'class-1',
    batteryWh: 400,
    weightLbs: 49,
    maxSystemWeightLbs: 330,
    salesModel: 'dealer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Mid-Range Compact' }],
  },
  {
    name: 'Tern Quick Haul Long D9',
    slug: 'tern-quick-haul-long-d9',
    brand: 'tern',
    category: 'cargo-bike',
    price: 3999,
    affiliateUrl: 'https://store.ternbicycles.com/products/quick-haul-long-d9',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'midtail',
    motorBrand: 'Bosch',
    motorPosition: 'mid-drive',
    motorNominalWatts: 250,
    motorTorqueNm: 85,
    motorType: 'Cargo Line (Bosch)',
    bikeClass: 'class-1',
    batteryWh: 500,
    weightLbs: 65,
    maxSystemWeightLbs: 419,
    salesModel: 'dealer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Mid-Range Midtail' }],
  },
  {
    name: 'Tern Orox',
    slug: 'tern-orox',
    brand: 'tern',
    category: 'cargo-bike',
    price: 6499,
    affiliateUrl: 'https://store.ternbicycles.com/products/orox-s12',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'longtail',
    motorBrand: 'Bosch',
    motorPosition: 'mid-drive',
    motorNominalWatts: 250,
    motorTorqueNm: 85,
    motorType: 'Performance Line CX (Bosch)',
    bikeClass: 'class-1',
    batteryWh: 545,
    weightLbs: 64,
    maxSystemWeightLbs: 463,
    salesModel: 'dealer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Premium Adventure Cargo' }],
  },
  {
    name: 'Tern Short Haul D8',
    slug: 'tern-short-haul-d8',
    brand: 'tern',
    category: 'cargo-bike',
    price: 1099,
    affiliateUrl: 'https://store.ternbicycles.com/products/short-haul-cargo-bike',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'compact',
    weightLbs: 35,
    maxSystemWeightLbs: 308,
    salesModel: 'dealer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Non-Electric Compact' }],
  },
  {
    name: 'Tern NBD',
    slug: 'tern-nbd',
    brand: 'tern',
    category: 'cargo-bike',
    price: 3599,
    affiliateUrl: 'https://store.ternbicycles.com/collections/nbd-e-bikes',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'longtail',
    motorBrand: 'Bosch',
    motorPosition: 'mid-drive',
    motorNominalWatts: 250,
    motorTorqueNm: 50,
    motorType: 'Active Plus / Performance (Bosch)',
    bikeClass: 'class-1',
    batteryWh: 400,
    weightLbs: 49,
    maxSystemWeightLbs: 309,
    salesModel: 'dealer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Utility' }],
  },
  {
    name: 'Trek Fetch+ 2',
    slug: 'trek-fetch-2',
    brand: 'trek',
    category: 'cargo-bike',
    price: 5999,
    affiliateUrl: 'https://www.trekbikes.com/us/en_US/bikes/cargo-bikes/fetch/fetch-2/p/42964/',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'longtail',
    motorBrand: 'Bosch',
    motorPosition: 'mid-drive',
    motorNominalWatts: 250,
    motorTorqueNm: 85,
    motorType: 'Performance CX / Cargo (Bosch)',
    bikeClass: 'class-1',
    batteryWh: 500,
    weightLbs: 68,
    maxSystemWeightLbs: 441,
    salesModel: 'dealer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Premium Longtail' }],
  },
  {
    name: 'Trek Fetch+ 4',
    slug: 'trek-fetch-4',
    brand: 'trek',
    category: 'cargo-bike',
    price: 8499,
    affiliateUrl: 'https://www.trekbikes.com/us/en_US/bikes/cargo-bikes/fetch/fetch-4/p/42961/',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'front-box',
    motorBrand: 'Bosch',
    motorPosition: 'mid-drive',
    motorNominalWatts: 250,
    motorTorqueNm: 85,
    motorType: 'Cargo Line (Bosch)',
    bikeClass: 'class-1',
    batteryWh: 750,
    weightLbs: 165,
    maxSystemWeightLbs: 551,
    salesModel: 'dealer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Premium Front-loader' }],
  },
  {
    name: 'Triobike Cargo / Cargo Big / Mono',
    slug: 'triobike-cargo-cargo-big-mono',
    brand: 'triobike',
    category: 'cargo-bike',
    price: 6000,
    affiliateUrl: 'https://triobike.com',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'front-box',
    motorBrand: 'Brose',
    motorPosition: 'mid-drive',
    motorNominalWatts: 250,
    motorTorqueNm: 90,
    motorType: '90Nm Mid-drive (Brose)',
    bikeClass: 'class-1',
    salesModel: 'dealer',
    availableIn: 'Limited',
    bestFor: [{ tag: 'Premium Front-loader' }],
  },
  {
    name: 'Urban Arrow Family Performance Line',
    slug: 'urban-arrow-family-performance-line',
    brand: 'urban-arrow',
    category: 'cargo-bike',
    price: 6999,
    affiliateUrl: 'https://www.urbanarrow.com/en-na/family',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'front-box',
    motorBrand: 'Bosch',
    motorPosition: 'mid-drive',
    motorNominalWatts: 250,
    motorTorqueNm: 75,
    motorType: 'Performance Line (Bosch)',
    bikeClass: 'class-1',
    batteryWh: 545,
    weightLbs: 106,
    maxSystemWeightLbs: 550,
    salesModel: 'dealer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Premium Front-loader' }],
  },
  {
    name: 'Urban Arrow Family Cargo Line',
    slug: 'urban-arrow-family-cargo-line',
    brand: 'urban-arrow',
    category: 'cargo-bike',
    price: 7999,
    affiliateUrl: 'https://www.urbanarrow.com/en-na/family',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'front-box',
    motorBrand: 'Bosch',
    motorPosition: 'mid-drive',
    motorNominalWatts: 250,
    motorTorqueNm: 85,
    motorType: 'Cargo Line (Bosch)',
    bikeClass: 'class-1',
    batteryWh: 545,
    weightLbs: 113,
    maxSystemWeightLbs: 550,
    salesModel: 'dealer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Premium Front-loader' }],
  },
  {
    name: 'Urban Arrow FamilyNext Pro',
    slug: 'urban-arrow-familynext-pro',
    brand: 'urban-arrow',
    category: 'cargo-bike',
    price: 8999,
    affiliateUrl: 'https://www.urbanarrow.com/en-na/familynext/',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'front-box',
    motorBrand: 'Bosch',
    motorPosition: 'mid-drive',
    motorNominalWatts: 250,
    motorTorqueNm: 85,
    motorType: 'Cargo Line Gen4 (Bosch)',
    bikeClass: 'class-1',
    batteryWh: 545,
    dualBatteryCapable: true,
    dualBatteryWh: 800,
    weightLbs: 112,
    maxSystemWeightLbs: 550,
    salesModel: 'dealer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Premium Front-loader' }],
  },
  {
    name: 'Velotric GoMad',
    slug: 'velotric-gomad',
    brand: 'velotric',
    category: 'cargo-bike',
    price: 1999,
    affiliateUrl: 'https://velotricbike.com/products/velotric-gomad-utility-ebike',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'compact',
    motorBrand: 'Generic',
    motorPosition: 'hub-rear',
    motorNominalWatts: 750,
    motorPeakWatts: 1300,
    motorTorqueNm: 85,
    motorType: '750W Hub (Generic)',
    bikeClass: 'class-2',
    batteryWh: 802,
    dualBatteryCapable: true,
    dualBatteryWh: 1600,
    weightLbs: 77,
    maxSystemWeightLbs: 500,
    salesModel: 'direct-to-consumer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Mid-Range Compact' }],
  },
  {
    name: 'Virtue Cycles Schoolbus+ / Courier+',
    slug: 'virtue-cycles-schoolbus-courier',
    brand: 'virtue-cycles',
    category: 'cargo-bike',
    price: 2999,
    affiliateUrl: 'https://virtuecycles.com',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'front-box',
    motorBrand: 'Generic',
    motorPosition: 'hub-rear',
    motorNominalWatts: 500,
    motorType: '250W/500W Hub (Generic)',
    bikeClass: 'class-1',
    batteryWh: 317,
    weightLbs: 145,
    cargoCapacityLbs: 250,
    salesModel: 'direct-to-consumer',
    availableIn: 'Limited',
    bestFor: [{ tag: 'Budget Front-loader Trike' }],
  },
  {
    name: 'Worksman Cycles Industrial Trike / Front Load',
    slug: 'worksman-cycles-industrial-trike-front-load',
    brand: 'worksman-cycles',
    category: 'cargo-bike',
    price: 509,
    affiliateUrl: 'https://www.worksmancycles.com',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'trike',
    salesModel: 'direct-to-consumer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Commercial Trike' }],
  },
  {
    name: 'Xtracycle RFA',
    slug: 'xtracycle-rfa',
    brand: 'xtracycle',
    category: 'cargo-bike',
    price: 3499,
    affiliateUrl: 'https://xtracycle.com/products/rfa-2',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'midtail',
    motorBrand: 'Shimano',
    motorNominalWatts: 250,
    motorTorqueNm: 85,
    motorType: 'STEPS EP6 / EP8 (Shimano)',
    bikeClass: 'class-1',
    batteryWh: 630,
    weightLbs: 60,
    maxSystemWeightLbs: 470,
    salesModel: 'direct-to-consumer',
    availableIn: 'In Stock (Sale)',
    bestFor: [{ tag: 'Mid-Range Midtail' }],
  },
  {
    name: 'Xtracycle Stoker',
    slug: 'xtracycle-stoker',
    brand: 'xtracycle',
    category: 'cargo-bike',
    price: 4499,
    affiliateUrl: 'https://xtracycle.com/products/estoker',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'longtail',
    motorBrand: 'Shimano',
    motorNominalWatts: 250,
    motorTorqueNm: 85,
    motorType: 'STEPS EP8 (Shimano)',
    bikeClass: 'class-1',
    batteryWh: 630,
    weightLbs: 65,
    maxSystemWeightLbs: 400,
    salesModel: 'direct-to-consumer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Mid-Range Longtail' }],
  },
  {
    name: 'Xtracycle Swoop ASM',
    slug: 'xtracycle-swoop-asm',
    brand: 'xtracycle',
    category: 'cargo-bike',
    price: 3999,
    affiliateUrl: 'https://xtracycle.com/collections/bikes',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'longtail',
    motorBrand: 'Shimano',
    motorNominalWatts: 250,
    motorTorqueNm: 85,
    motorType: 'EP6 + Di2 Auto-shift (Shimano)',
    bikeClass: 'class-3',
    batteryWh: 630,
    weightLbs: 63,
    maxSystemWeightLbs: 470,
    salesModel: 'direct-to-consumer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Mid-Range Longtail' }],
  },
  {
    name: 'Xtracycle Hopper',
    slug: 'xtracycle-hopper',
    brand: 'xtracycle',
    category: 'cargo-bike',
    price: 2499,
    affiliateUrl: 'https://xtracycle.com/products/hopper-compact-cargo',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'midtail',
    motorBrand: 'Generic',
    motorPosition: 'hub-rear',
    motorNominalWatts: 750,
    motorType: '750W Hub (Generic)',
    bikeClass: 'class-2',
    batteryWh: 720,
    weightLbs: 87,
    maxSystemWeightLbs: 500,
    salesModel: 'direct-to-consumer',
    availableIn: 'In Stock (Sale)',
    bestFor: [{ tag: 'Mid-Range Midtail' }],
  },
  {
    name: 'Yuba Spicy Curry V4',
    slug: 'yuba-spicy-curry-v4',
    brand: 'yuba',
    category: 'cargo-bike',
    price: 5999,
    affiliateUrl: 'https://yubabikes.com/product/spicy-curry/',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'longtail',
    motorBrand: 'Bosch',
    motorPosition: 'mid-drive',
    motorNominalWatts: 250,
    motorTorqueNm: 85,
    motorType: 'Cargo Line (Bosch)',
    bikeClass: 'class-1',
    batteryWh: 500,
    weightLbs: 70,
    maxSystemWeightLbs: 440,
    salesModel: 'dealer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Premium Longtail' }],
  },
  {
    name: 'Yuba Boda Boda',
    slug: 'yuba-boda-boda',
    brand: 'yuba',
    category: 'cargo-bike',
    price: 5249,
    affiliateUrl: 'https://yubabikes.com/product/boda-boda/',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'midtail',
    motorBrand: 'Bosch',
    motorPosition: 'mid-drive',
    motorNominalWatts: 250,
    motorTorqueNm: 85,
    motorType: 'Cargo Line (Bosch)',
    bikeClass: 'class-1',
    batteryWh: 500,
    weightLbs: 70,
    maxSystemWeightLbs: 440,
    salesModel: 'dealer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Premium Compact Midtail' }],
  },
  {
    name: 'Yuba FastRack V2',
    slug: 'yuba-fastrack-v2',
    brand: 'yuba',
    category: 'cargo-bike',
    price: 3999,
    affiliateUrl: 'https://yubabikes.com/product/fastrack/',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'midtail',
    motorBrand: 'Shimano',
    motorNominalWatts: 250,
    motorType: 'STEPS E7000 (Shimano)',
    bikeClass: 'class-1',
    batteryWh: 500,
    weightLbs: 76,
    maxSystemWeightLbs: 440,
    salesModel: 'dealer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Mid-Range Compact Midtail' }],
  },
  {
    name: 'Yuba Kombi E5',
    slug: 'yuba-kombi-e5',
    brand: 'yuba',
    category: 'cargo-bike',
    price: 2999,
    affiliateUrl: 'https://yubabikes.com/product/kombi-e5/',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'midtail',
    motorBrand: 'Shimano',
    motorNominalWatts: 250,
    motorType: 'STEPS E5000 (Shimano)',
    bikeClass: 'class-1',
    batteryWh: 418,
    weightLbs: 67,
    maxSystemWeightLbs: 440,
    salesModel: 'dealer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Mid-Range Compact Midtail' }],
  },
  {
    name: 'Yuba Kombi (Non-Electric)',
    slug: 'yuba-kombi-non-electric',
    brand: 'yuba',
    category: 'cargo-bike',
    price: 800,
    affiliateUrl: 'https://yubabikes.com/product/kombi/',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'midtail',
    weightLbs: 53,
    maxSystemWeightLbs: 440,
    salesModel: 'dealer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Non-Electric Compact Midtail' }],
  },
  {
    name: 'Yuba Mundo EP8',
    slug: 'yuba-mundo-ep8',
    brand: 'yuba',
    category: 'cargo-bike',
    price: 4499,
    affiliateUrl: 'https://yubabikes.com/product/mundo-ep8-10s/',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'longtail',
    motorBrand: 'Shimano',
    motorNominalWatts: 250,
    motorType: 'STEPS EP8 (Shimano)',
    bikeClass: 'class-1',
    batteryWh: 504,
    weightLbs: 70,
    maxSystemWeightLbs: 550,
    salesModel: 'dealer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Mid-Range Longtail' }],
  },
  {
    name: 'Yuba Mundo Lux (Non-Electric)',
    slug: 'yuba-mundo-lux-non-electric',
    brand: 'yuba',
    category: 'cargo-bike',
    price: 1299,
    affiliateUrl: 'https://yubabikes.com/product/mundo-lux/',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'longtail',
    weightLbs: 54,
    maxSystemWeightLbs: 550,
    salesModel: 'dealer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Non-Electric Longtail' }],
  },
  {
    name: 'Yuba SuperCargo CL',
    slug: 'yuba-supercargo-cl',
    brand: 'yuba',
    category: 'cargo-bike',
    price: 5999,
    affiliateUrl: 'https://yubabikes.com/product/supercargo-cl/',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'front-box',
    motorBrand: 'Bosch',
    motorPosition: 'mid-drive',
    motorNominalWatts: 250,
    motorTorqueNm: 85,
    motorType: 'Cargo Line (Bosch)',
    bikeClass: 'class-1',
    batteryWh: 500,
    weightLbs: 77,
    maxSystemWeightLbs: 440,
    salesModel: 'dealer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Premium Front-loader' }],
  },
  {
    name: 'Yuba SuperCargo (Non-Electric)',
    slug: 'yuba-supercargo-non-electric',
    brand: 'yuba',
    category: 'cargo-bike',
    price: 2999,
    affiliateUrl: 'https://yubabikes.com/product/supercargo/',
    testingStatus: 'specs-only',
    imageStatus: 'needs-images',
    cargoLayout: 'front-box',
    weightLbs: 60,
    maxSystemWeightLbs: 440,
    salesModel: 'dealer',
    availableIn: 'In Stock',
    bestFor: [{ tag: 'Non-Electric Front-loader' }],
  },
]

// ─── Main ───

async function main() {
  log(`Targeting: ${BASE_URL}`)
  log(`${brands.length} brands, ${products.length} products to seed`)

  const token = await login()

  // Upsert brands
  log('--- Upserting brands ---')
  const brandIdMap: Record<string, number> = {}

  for (const brand of brands) {
    const existing = await findBySlug('brands', brand.slug, token)
    if (existing) {
      log(`  Brand "${brand.name}" exists (id=${existing.id}), skipping`)
      brandIdMap[brand.slug] = existing.id
    } else {
      const doc = await createDoc('brands', brand, token)
      log(`  Created brand "${brand.name}" (id=${doc.doc.id})`)
      brandIdMap[brand.slug] = doc.doc.id
    }
  }

  // Create products
  log('--- Seeding products ---')
  let created = 0
  let skipped = 0

  for (const product of products) {
    const existing = await findBySlug('products', product.slug, token)
    if (existing) {
      log(`  "${product.name}" already exists (id=${existing.id}), skipping`)
      skipped++
      continue
    }

    const brandId = brandIdMap[product.brand]
    const { brand: _brand, ...rest } = product

    try {
      const doc = await createDoc(
        'products',
        {
          ...rest,
          brand: brandId || undefined,
          _status: 'published',
          publishedAt: new Date().toISOString(),
        },
        token,
      )
      log(`  Created "${product.name}" (id=${doc.doc.id})`)
      created++
    } catch (err: any) {
      log(`  FAILED "${product.name}": ${err.message}`)
    }
  }

  log(`\nDone! Created: ${created}, Skipped: ${skipped}, Total: ${products.length}`)
}

main().catch((err) => {
  console.error('[seed-xlsx] Fatal error:', err)
  process.exit(1)
})
